version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: configService.get<string>('DB_PASSWORD')
      POSTGRES_USER: configService.get<string>('DB_USERNAME')
      POSTGRES_DB: configService.get<string>('DB_DATABASE')
    ports:
      - '5432:5432'

  