version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: configService.get<string>('DB_PASSWORD')
      POSTGRES_USER: configService.get<string>('DB_USERNAME')
      POSTGRES_DB: configService.get<string>('DB_DATABASE')
    ports:
      - '5432:5432'

  